development:
  adapter: mysql2
  database: rails_dev
  username: dev
  password: devpwd

test:
  adapter: mysql2
  database: rails_test
  username: test
  password: testpwd

production:
  #database_url: mysql://mysql:b5cde8c9bff96999@dokku-mysql-rails-prod:3306/rails_prod
  host: dokku-mysql-rails-prod.ec2-54-77-106-4.eu-west-1.compute.amazonaws.com
  port: 3306	
  adapter: mysql2
  database: rails_prod
  username: mysql
  password: b5cde8c9bff96999
  
