development:
  adapter: mysql2
  database: rails_dev
  username: dev
  password: devpwd

test:
  adapter: mysql2
  database: rails_test
  username: tester
  password: testpwd

production:
  port: 3306	
  adapter: mysql2
  database: rails_prod
  username: prod
  password: prodpwd
  
