development:
  adapter: mysql2
  database: rails_dev
  username: dev
  password: devpwd

test:
  adapter: mysql2
  database: rails_test
  username: test
  password: testpwd

production:
  url: mysql://mysql:b5cde8c9bff96999@dokku-mysql-rails-prod:3306/rails_prod
  adapter: mysql2
  database: rails_prod
  username: prod
  password: prodpwd
